/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas;

import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.Arrays;
import static javax.accessibility.AccessibleRole.SEPARATOR;
import javax.swing.JFileChooser;
import javax.swing.Timer;
import javax.swing.filechooser.FileNameExtensionFilter;
import proyecto2J.MonticuloBinario;
import proyecto2J.NodoDocumento;


public class Arbol extends javax.swing.JFrame {

    public static MonticuloBinario bh;

    /**
     * Creates new form Ventana1
     */
    public Arbol(MonticuloBinario h) {
        this.bh = h;
        initComponents();
        
        
    }
    public void graficar(Graphics g, int m, int y, NodoDocumento x){
        g.setColor(Color.WHITE);
        g.fillOval(m, y, 50, 40);
        g.setColor(Color.BLACK);
        g.setFont(new Font("Times New Roman",Font.BOLD,20));
        String t = String.valueOf(x.getTiempo_impresion());
        g.drawString(t, m+20, y+30);
    }
    public int graficarMonticulo(Graphics g, NodoDocumento x, int x0, int x1, int y, int index){

        int m = (x0 + x1) / 2;
        g.setColor(Color.WHITE);
        g.fillOval(m, y, 50, 40);
        g.setColor(Color.GRAY);
        g.setFont(new Font("Arial",Font.BOLD,20));
        String t = String.valueOf(x.getTiempo_impresion());
        g.drawString(t, m+20, y+30);
        int posL = bh.indiceIzquierdo(index);
        int posR = bh.indiceDerecho(index);
        if (bh.getMonticuloBinario()[posL] != null) {
            int x2 = graficarMonticulo(g, bh.getMonticuloBinario()[posL],x0,m,y+50, posL);
            g.drawLine(m+25, y+40, x2+25, y+50);
        }
        if (bh.getMonticuloBinario()[posR] != null) {
            int x2 = graficarMonticulo(g, bh.getMonticuloBinario()[posR],m,x1,y+50, posR);
            g.drawLine(m+25, y+40, x2+25, y + 50);
        }
        return m;
    }



    @Override
    public void paint(Graphics g) {
        super.paint(g);
        graficarMonticulo(g, bh.getMonticuloBinario()[0], 0, this.getWidth()-25, 100, 0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(51, 51, 255));
        jButton1.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("SALIR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 30, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1230, 730));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Arbol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Arbol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Arbol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Arbol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Arbol(  bh).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
